### ISSUE TITLE
建议添加12306验证码识别接口

### ISSUE THREAD

**Issue by 12374598858** [JohnnyZhang0628/12306GoHome#1]
https://12306.jiedanba.cn/12306

**Comment by JohnnyZhang0628** [comment]
@12374598858 这个不错，我联系一下作者，看看允许我调用他的接口吗

**Comment by 12374598858** [comment]
@JohnnyZhang0628  我就是作者啊

**Comment by JohnnyZhang0628** [comment]
@12374598858 那我就调用你这个接口了  https://12306.jiedanba.cn/api/v2/img_vcode
