### ISSUE TITLE
抢票 这个是失败了吗

### ISSUE THREAD

**Issue by 834852170** [JohnnyZhang0628/12306GoHome#3]
![11111](https://user-images.githubusercontent.com/32630442/149449450-21027122-5861-4ff3-88c0-89ce3bebebc3.png)

**Comment by 834852170** [comment]
上面的问题应该是关闭弹框事件  我把代码注释了 
现在还有另外一个问题就是  当城市名称拼音相同时  怎么定位我要的城市呀

**Comment by 834852170** [comment]
以上两个问题 已经搞定 非常感谢 
两个点 不知目前是否支持 
1、多人购多张票？
2、支持选座？

**Comment by JohnnyZhang0628** [comment]
> 以上两个问题 已经搞定 非常感谢 两个点 不知目前是否支持 1、多人购多张票？ 2、支持选座？
1、支持多个人。在app.config文件下面，passengerName 属性设置 张三,李四,王五。以,分割。
2、选中目前不支持，抢票能抢到票就不错了。如果你要选座说明票源充足，你直接去12306官网购买
